# Folder
.github/**
plop/**
.husky/**
.nx/**

# Files
.czrc
.editorconfig
.gitattributes
.gitignore
.lintstagedrc.cjs
.lintstagedrc.cjs
.npmignore
.nxignore
.prettierignore
.prettierrc.cjs
.secretlintignore
.secretlintrc.cjs
.textlintignore
.textlintrc
.yamllint.yaml
audit-ci.jsonc
codecov.yml
commitlint.config.cjs
nx.json
plop.js
pnpm-lock.yaml
pnpm-workspace.yaml
taze.config.js
tsconfig.base.json
tsconfig.eslint.json
tsconfig.json
