packages:
  - '!**/__test__/**'
  - '!**/__tests__/**'
  - '!**/__fixtures__/**'
  - packages/**
  - '!packages/multi-semantic-release/__fixtures__/**'

catalogs:
  build:
    esbuild: 0.27.0
  cli:
    '@anolilab/semantic-release-clean-package-json': 4.0.0-alpha.2
    '@anolilab/semantic-release-pnpm': 3.0.0-alpha.2
    '@sebbo2002/semantic-release-jsr': ^3.1.0
    '@semantic-release/changelog': ^6.0.3
    '@semantic-release/commit-analyzer': 13.0.1
    '@semantic-release/error': ^4.0.0
    '@semantic-release/exec': ^7.1.0
    '@semantic-release/git': ^10.0.1
    '@semantic-release/github': ^12.0.2
    '@semantic-release/npm': ^13.1.2
    '@semantic-release/release-notes-generator': 14.1.0
    commitizen: ^4.3.1
    semantic-release: ^25.0.2
    semantic-release-yarn: ^3.0.2
    taze: ^19.9.2
  dev:
    '@arethetypeswrong/cli': ^0.18.2
    '@ckeditor/typedoc-plugins': 43.1.0
    '@visulima/packem': 2.0.0-alpha.49
    conventional-changelog-conventionalcommits: 9.1.0
    dockerode: 4.0.9
    file-url: ^4.0.0
    get-stream: 9.0.1
    got: ^14.6.5
    left-pad: latest
    p-retry: ^7.1.0
    stream-buffers: ^3.0.3
    tempy: ^3.1.0
    type-fest: ^5.3.1
    typedoc: 0.28.15
    typedoc-plugin-rename-defaults: 0.7.3
  icons:
    cosmiconfig: ^9.0.0
  lint:
    '@anolilab/commitlint-config': ^8.1.0
    '@anolilab/eslint-config': ^16.4.4
    '@anolilab/lint-staged-config': ^4.0.1
    '@anolilab/prettier-config': ^8.0.1
    '@anolilab/textlint-config': ^11.1.0
    '@commitlint/cli': ^20.3.1
    '@commitlint/config-conventional': ^20.3.1
    '@secretlint/secretlint-rule-preset-recommend': ^11.2.5
    eslint: 9.39.1
    eslint-plugin-you-dont-need-lodash-underscore: 6.14.0
    husky: ^9.1.7
    lint-staged: ^16.2.7
    prettier: ^3.7.4
    publint: ^0.3.16
    secretlint: 11.2.5
    textlint: ^15.5.0
  markdown:
    typedoc-plugin-markdown: 4.9.0
  monorepo:
    '@nx/workspace': 22.3.3
    nx: ^22.3.3
  network:
    browserslist-config-anolilab: ^7.0.1
  node:
    '@visulima/path': ^2.0.5
    cross-env: ^10.1.0
    execa: ^9.6.1
    pkg-pr-new: ^0.0.62
    resolve-from: ^5.0.0
    rimraf: ^6.1.2
  peer:
    left-pad: latest
  prod:
    '@actions/core': ^2.0.0
    '@anolilab/rc': 3.0.0-alpha.2
    '@babel/core': ^7.28.5
    '@semrel-extra/topo': ^1.14.1
    '@visulima/fs': ^4.1.0
    '@visulima/package': ^4.1.7
    audit-ci: ^7.1.0
    blork: ^9.3.0
    conventional-changelog-conventionalcommits: 9.1.0
    debug: ^4.4.3
    detect-indent: ^7.0.2
    detect-newline: ^4.0.1
    env-ci: ^11.2.0
    git-log-parser: ^1.2.1
    ini: ^6.0.0
    is-ci: ^4.1.0
    normalize-url: ^8.1.0
    plop: ^4.0.4
    registry-auth-token: ^5.1.0
    signale: ^1.4.0
    sort-package-json: ^3.6.0
    stream-buffers: ^3.0.3
    yaml: ^2.8.2
    yargs: 18.0.0
  test:
    '@vitest/coverage-v8': ^4.0.15
    '@vitest/ui': ^4.0.15
    vitest: ^4.0.16
  tsc:
    typescript: ^5.9.3
  types:
    '@types/debug': 4.1.12
    '@types/dockerode': ^3.3.47
    '@types/env-ci': 3.1.4
    '@types/git-log-parser': 1.2.3
    '@types/ini': ^4.1.1
    '@types/lodash-es': 4.17.12
    '@types/node': 24.10.1
    '@types/semantic-release__error': 3.0.3
    '@types/semver': 7.7.1
    '@types/signale': 1.4.7
    '@types/stream-buffers': 3.0.7
    '@types/yargs': 17.0.34
  utils:
    lodash-es: ^4.17.21
    semver: ^7.7.3
    ts-deepmerge: ^7.0.3

dedupeInjectedDeps: true

disallowWorkspaceCycles: true

ignoreWorkspaceCycles: false

includeWorkspaceRoot: false

injectWorkspacePackages: false

linkWorkspacePackages: true

minimumReleaseAgeExclude:
  - vitest
  - '@vitest/*'
  - typescript
  - '@types/*'

onlyBuiltDependencies:
  - cpu-features
  - esbuild
  - nx
  - oxc-resolver
  - protobufjs
  - rs-module-lexer
  - ssh2
  - unrs-resolver

overrides:
  '@modelcontextprotocol/sdk@<1.25.2': '>=1.25.2'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  chrono-node@<2.2.4: '>=2.9.0'
  qs@<6.14.1: '>=6.14.1'
  tar-fs@>=2.0.0 <2.1.4: '>=3.1.1'
  tmp@<=0.2.3: '>=0.2.5'
  vite@>=7.1.0 <=7.1.10: '>=7.2.7'

preferWorkspacePackages: true

saveWorkspaceProtocol: true

sharedWorkspaceLockfile: true
