packages:
  - '!**/__test__/**'
  - '!**/__tests__/**'
  - '!**/__fixtures__/**'
  - packages/**
  - '!packages/multi-semantic-release/__fixtures__/**'

catalogs:
  build:
    esbuild: 0.25.10
  cli:
    '@anolilab/multi-semantic-release': ^2.0.5
    '@anolilab/semantic-release-clean-package-json': 3.0.4
    '@anolilab/semantic-release-pnpm': 2.0.4
    '@semantic-release/changelog': ^6.0.3
    '@semantic-release/commit-analyzer': 13.0.1
    '@semantic-release/error': ^4.0.0
    '@semantic-release/exec': ^7.1.0
    '@semantic-release/git': ^10.0.1
    '@semantic-release/github': ^11.0.6
    '@semantic-release/npm': ^13.0.0
    '@semantic-release/release-notes-generator': 14.1.0
    commitizen: ^4.3.1
    semantic-release: ^24.2.9
    semantic-release-yarn: ^3.0.2
    taze: ^19.7.0
  database:
    normalize-url: ^8.1.0
  dev:
    '@arethetypeswrong/cli': ^0.18.2
    '@ckeditor/typedoc-plugins': 43.1.0
    '@visulima/packem': 2.0.0-alpha.20
    conventional-changelog-conventionalcommits: 9.1.0
    dockerode: 4.0.8
    file-url: ^4.0.0
    get-stream: 9.0.1
    got: ^14.4.9
    left-pad: latest
    p-retry: ^7.0.0
    stream-buffers: ^3.0.3
    tempy: ^3.1.0
    type-fest: ^5.0.1
    typedoc: 0.28.13
    typedoc-plugin-rename-defaults: 0.7.3
  icons:
    cosmiconfig: ^9.0.0
  lint:
    '@anolilab/commitlint-config': ^6.0.5
    '@anolilab/eslint-config': ^16.3.3
    '@anolilab/lint-staged-config': ^3.0.34
    '@anolilab/prettier-config': ^6.0.6
    '@anolilab/textlint-config': ^9.0.7
    '@commitlint/cli': ^20.1.0
    '@commitlint/config-conventional': ^20.0.0
    '@secretlint/secretlint-rule-preset-recommend': ^11.2.4
    eslint: 9.36.0
    eslint-plugin-you-dont-need-lodash-underscore: 6.14.0
    husky: ^9.1.7
    lint-staged: ^16.2.3
    prettier: ^3.6.2
    publint: ^0.3.14
    secretlint: 11.2.4
    textlint: ^15.2.2
  markdown:
    typedoc-plugin-markdown: 4.9.0
  monorepo:
    '@nx/workspace': 21.5.3
    nx: ^21.6.3
  network:
    browserslist-config-anolilab: ^6.0.5
  node:
    '@visulima/path': ^1.4.0
    cross-env: ^10.1.0
    execa: ^9.6.0
    pkg-pr-new: ^0.0.60
    resolve-from: ^5.0.0
    rimraf: ^6.0.1
  peer:
    left-pad: latest
  prod:
    '@anolilab/rc': 2.0.4
    '@babel/core': ^7.28.4
    '@semrel-extra/topo': ^1.14.1
    '@visulima/fs': ^3.1.9
    '@visulima/package': ^4.0.2
    audit-ci: ^7.1.0
    blork: ^9.3.0
    conventional-changelog-conventionalcommits: 9.1.0
    debug: ^4.4.3
    detect-indent: ^7.0.2
    detect-newline: ^4.0.1
    git-log-parser: ^1.2.1
    ini: ^5.0.0
    is-ci: ^4.1.0
    plop: ^4.0.4
    registry-auth-token: ^5.1.0
    signale: ^1.4.0
    sort-package-json: ^3.4.0
    stream-buffers: ^3.0.3
    yargs: 18.0.0
  test:
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    vitest: ^3.2.4
  tsc:
    typescript: ^5.9.3
  types:
    '@types/dockerode': ^3.3.44
    '@types/ini': ^4.1.1
    '@types/node': 24.6.2
    '@types/semantic-release': ^21.1.0
    '@types/semantic-release__error': 3.0.3
    '@types/semver': 7.7.1
    '@types/stream-buffers': ^3.0.7
  utils:
    lodash-es: ^4.17.21
    semver: ^7.7.2
    ts-deepmerge: ^7.0.3

onlyBuiltDependencies:
  - cpu-features
  - esbuild
  - nx
  - oxc-resolver
  - protobufjs
  - rs-module-lexer
  - ssh2
  - unrs-resolver

overrides:
  chrono-node@<2.2.4: '>=2.9.0'
  tar-fs@>=2.0.0 <2.1.4: '>=2.1.4'
  tmp@<=0.2.3: '>=0.2.5'
