name: "AlloAllo"

on: # yamllint disable-line rule:truthy
    issues:
        types:
            - "opened"
    pull_request_target:
        branches:
            - "main"
        types:
            - "opened"
            - "closed"

permissions:
    contents: "read"

jobs:
    allo-allo:
        uses: "anolilab/workflows/.github/workflows/allo-allo.yml@3951efd646a078e384e881c3579e9f92927d240e" # main
        with:
            target-repo: "anolilab/semantic-release"
            onboarding-lead: "prisis"
