name: "AlloAllo"

on: # yamllint disable-line rule:truthy
    issues:
        types:
            - "opened"
    pull_request_target:
        branches:
            - "main"
        types:
            - "opened"
            - "closed"

jobs:
    allo-allo:
        uses: "anolilab/workflows/.github/workflows/allo-allo.yml@6f532c500cfe608e2cc5ff59413161b7a1294de7" # main
        with:
            target-repo: "anolilab/semantic-release"
            onboarding-lead: "prisis"
