name: "AlloAllo"

on: # yamllint disable-line rule:truthy
    issues:
        types:
            - "opened"
    pull_request_target:
        branches:
            - "main"
        types:
            - "opened"
            - "closed"

permissions:
    contents: "read"

jobs:
    allo-allo:
        uses: "anolilab/workflows/.github/workflows/allo-allo.yml@0902480949db1f1d6516f0cc3f8ce245b4242ade" # main
        with:
            target-repo: "anolilab/semantic-release"
            onboarding-lead: "prisis"
