name: "Cleanup caches by a branch"

on: # yamllint disable-line rule:truthy
    pull_request:
        types:
            - "closed"

permissions:
    contents: "read"

jobs:
    cleanup-branch-cache:
        uses: "anolilab/workflows/.github/workflows/cleanup-branch-cache.yaml@0902480949db1f1d6516f0cc3f8ce245b4242ade" # main
        with:
            target-repo: "anolilab/semantic-release"
