name: "Cleanup caches by a branch"

on: # yamllint disable-line rule:truthy
    pull_request:
        types:
            - "closed"

permissions:
    contents: "read"

jobs:
    cleanup-branch-cache:
        uses: "anolilab/workflows/.github/workflows/cleanup-branch-cache.yaml@bbe85cc99b036e08d0ac7daf7be586218d8e2d0c" # main
        with:
            target-repo: "anolilab/semantic-release"
