name: "Dependency review"
on: # yamllint disable-line rule:truthy
    pull_request:
        branches: ["main"]
permissions: {}
jobs:
    dependency-review:
        permissions:
            contents: "read"
            pull-requests: "write"
        uses: "anolilab/workflows/.github/workflows/dependency-review.yml@5b340a228896b01f6d2b6f3bf3b574caed9ee89b" # v15.3.1+
