name: "Lint"
on: # yamllint disable-line rule:truthy
    pull_request:
        branches: ["main"]
    merge_group: # yamllint disable-line rule:empty-values
permissions: {}
jobs:
    lint:
        permissions:
            contents: "read"
            pull-requests: "read"
        uses: "anolilab/workflows/.github/workflows/lint.yml@2bd348c5c236a10db670232e5b08619ccbaf55b3" # v21.0.5
        with:
            lint_eslint: true
            lint_types: true
            lint_attw: false
            lint_package_json: true
            lint_markdown: false
            lint_yaml: true
            lint_actionlint: true
            lint_rust: false
            node_version: "22"
