name: "Lint"
on:
    pull_request:
        branches: ["main"]
permissions: {}
jobs:
    lint:
        permissions:
            contents: "read"
            pull-requests: "read"
        uses: "anolilab/workflows/.github/workflows/lint.yml@20b8733e71ebbb165d54fe8cede47e225985a58a" # v15.3.1+
        with:
            lint_eslint: true
            lint_types: true
            lint_attw: false
            lint_package_json: true
            lint_markdown: true
            lint_yaml: true
            lint_actionlint: true
            lint_rust: false
            node_version: "22"
