name: "Lint"
on: # yamllint disable-line rule:truthy
    pull_request:
        branches: ["main"]
permissions: {}
jobs:
    lint:
        permissions:
            contents: "read"
            pull-requests: "read"
        uses: "anolilab/workflows/.github/workflows/lint.yml@1dc687e78887af5536dbd0877054fc1c56c5575b" # v15.3.1+
        with:
            lint_eslint: true
            lint_types: true
            lint_attw: false
            lint_package_json: true
            lint_markdown: true
            lint_yaml: true
            lint_actionlint: true
            lint_rust: false
            node_version: "22"
