name: "Lock inactive issues and pull requests"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 * * * *"

permissions:
    contents: "read"
    discussions: "write"
    issues: "write"
    pull-requests: "write"

jobs:
    lock-closed:
        uses: "anolilab/workflows/.github/workflows/lock-closed.yml@3951efd646a078e384e881c3579e9f92927d240e" # main
        with:
            target-repo: "anolilab/semantic-release"
