name: "Lock File Maintenance"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 */3 * * *" # At minute 0 past every 3rd hour.
    pull_request:
        branches:
            - "dependabot/**"
    workflow_dispatch: # yamllint disable-line rule:empty-values

permissions:
    contents: "write" # for checkout and lock file updates

jobs:
    lock-file:
        uses: "anolilab/workflows/.github/workflows/pnpm-lock-file-maintenance.yml@bbe85cc99b036e08d0ac7daf7be586218d8e2d0c" # main
        with:
            target-repo: "anolilab/semantic-release"
            node-version: "22.x"
            run-audit-fix: false
        secrets:
            github-token: "${{ secrets.LOCK_MAINTENANCE_GITHUB_TOKEN }}"
