name: "Lock inactive issues and pull requests"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 * * * *"

permissions:
    contents: "read"
    issues: "write"

jobs:
    lock-closed:
        uses: "anolilab/workflows/.github/workflows/lock-closed.yml@0902480949db1f1d6516f0cc3f8ce245b4242ade" # main
        with:
            target-repo: "anolilab/semantic-release"
