name: "Lock File Maintenance"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 */3 * * *" # At minute 0 past every 3rd hour.
    pull_request:
        branches:
            - "dependabot/**"
    workflow_dispatch: # yamllint disable-line rule:empty-values

permissions:
    contents: "write" # for checkout and lock file updates

jobs:
    lock-file:
        uses: "anolilab/workflows/.github/workflows/pnpm-lock-file-maintenance.yml@0902480949db1f1d6516f0cc3f8ce245b4242ade" # main
        with:
            target-repo: "anolilab/semantic-release"
            node-version: "22.x"
            run-audit-fix: true
        secrets:
            github-token: "${{ secrets.LOCK_MAINTENANCE_GITHUB_TOKEN }}"
