name: "Require 'Allow Edits'"

on: ["pull_request_target", "merge_group"] # yamllint disable-line rule:truthy

permissions:
    contents: "read"

jobs:
    check_allow_edits:
        timeout-minutes: 10
        permissions:
            pull-requests: "read" # for ljharb/require-allow-edits to check 'allow edits' on PR

        name: "Require “Allow Edits”"

        runs-on: "ubuntu-latest"

        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40" # v2.19.0
              with:
                  egress-policy: "audit"

            - uses: "ljharb/require-allow-edits@13f90bc8cc5de000f2b44a0e2c3a11d108e8cd9f" # v2.0.1
