name: "Scorecards supply-chain security"
on:
    branch_protection_rule:
    schedule:
        - cron: "37 14 * * 6"
    push:
        branches: ["main"]
permissions: {}
jobs:
    scorecards:
        permissions:
            security-events: "write"
            id-token: "write"
            actions: "read"
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/scorecards.yml@20b8733e71ebbb165d54fe8cede47e225985a58a" # v15.3.1+
        with:
            branch: "main"
            publish_results: true
