name: "Label Idle Issues"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

permissions:
    contents: "read"
    issues: "write"
    pull-requests: "write"

jobs:
    stale-issues:
        uses: "anolilab/workflows/.github/workflows/stale-issues.yml@6d0f01d0742f15c51b2398bc97e0b008c7416b00" # main
        with:
            target-repo: "anolilab/semantic-release"
