name: "Label Idle Issues"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

permissions:
    contents: "read"
    issues: "write"
    pull-requests: "write"

jobs:
    stale-issues:
        uses: "anolilab/workflows/.github/workflows/stale-issues.yml@2bd348c5c236a10db670232e5b08619ccbaf55b3" # v21.0.5 # main
        with:
            target-repo: "anolilab/semantic-release"
