name: "Label Idle Issues"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

jobs:
    stale-issues:
        uses: "anolilab/workflows/.github/workflows/stale-issues.yml@9212260a922e37110bc90c281b7376197de2807d" # main
        with:
            target-repo: "anolilab/semantic-release"
