name: "Zizmor"
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
permissions: {}
jobs:
    zizmor:
        permissions:
            security-events: "write"
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/zizmor.yml@3bd9e3be8b2c419cf0e9237c1e78ab9a5e68bafa" # v15.1.3+
        with:
            min_severity: "medium"
