name: "Zizmor"
on: # yamllint disable-line rule:truthy
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
permissions: {}
jobs:
    zizmor:
        permissions:
            security-events: "write"
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/zizmor.yml@ffe1f9c618304dee645c2821890ec3f0a91f67b3" # v21.0.0
        with:
            min_severity: "medium"
